trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: 'Self-Hosted Agent Pool'  # Replace 'ubuntu-latest' with your self-hosted agent pool name

steps:
- task: UseNode@1  # Use Node.js task to set up the Node.js environment
  inputs:
    versionSpec: '16.x'
    addToPath: true

- script: |
    npm install  # Install dependencies
    npx playwright test  # Run the Playwright tests
  displayName: 'Install dependencies and run tests'

- task: PublishTestResults@2  # Publish test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results/*.xml'
    mergeTestResults: true
    testRunTitle: 'Playwright Test Run'
