trigger:
  branches:
    include:
      - main  # Adjust to your desired branch(es)

pool:
  name: 'Self-Hosted Agent Pool'  # Make sure this is the correct agent pool name

steps:
- task: UseNode@1  # Example task: setup Node.js environment
  inputs:
    versionSpec: '16.x'
    addToPath: true

- script: |
    npm install
    npx playwright test
  displayName: 'Install dependencies and run tests'
